services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeMeInProd!
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: